site_name: StatsCan
theme:
  name: material
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            docstring_section_style: table
            preload_modules:
              - typing
              - stats_can
            members_order: source
            docstring_style: numpy
            show_root_headings: true
            show_symbol_type_heading: true
            heading_level: 3
            show_source: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            inheritance: true
            unwrap_annotated: true
markdown_extensions:
  - pymdownx.magiclink # Helps with auto-linking URLs
  - pymdownx.betterem # Minor styling improvement
  - markdown_include.include:
      base_path: .
  - admonition
  - fenced_code
nav:
  - Home: index.md
  - API:
      - scwds: api/scwds.md
      - sc: api/sc.md
      - schemas: api/schemas.md
